package com.jfxy.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import com.jfxy.listener.MemoryListener;
import com.jfxy.util.DateUtil;
import com.jfxy.util.StringUtil;

public class Mem implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memcard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemPassword
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String mempassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemName
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemSex
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memsex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemIdentityCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memidentitycard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemMobile
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memmobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemPhoto
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memphoto;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemBirthdayType
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer membirthdaytype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemBirthday
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String membirthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemIsPast
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memispast;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemPastTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String mempasttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemPoint
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer mempoint;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemPointAutomatic
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer mempointautomatic;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemMoney
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private BigDecimal memmoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemConsumeMoney
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private BigDecimal memconsumemoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemConsumeLastTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Date memconsumelasttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemConsumeCount
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memconsumecount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemEmail
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String mememail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemAddress
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memaddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemState
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memstate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemRecommendID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memrecommendid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemLevelID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memlevelid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemShopID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memshopid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCreateTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Date memcreatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemRemark
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memremark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemUserID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memuserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemTelePhone
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memtelephone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemQRCode
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memqrcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemProvince
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memprovince;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCity
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memcity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCounty
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memcounty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemVillage
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memvillage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemQuestion
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memquestion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemAnswer
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memanswer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemWeiXinCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memweixincard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCardNumber
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memcardnumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemAttention
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private Integer memattention;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemWeiXinCards
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private String memweixincards;

	/**
	 * shopname
	 */
	private String shopname;

	/**
	 * levelname
	 */
	private String levelname;

	/**
	 * consumemoney
	 */
	private BigDecimal consumemoney;

	/**
	 * memcountnumber
	 */
	private double memcountnumber;

	/**
	 * username
	 */
	private String username;

	private Map<String, String> map = new HashMap<String, String>();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table mem
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemID
	 *
	 * @return the value of mem.MemID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemid() {
		return memid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemID
	 *
	 * @param memid
	 *            the value for mem.MemID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemid(Integer memid) {
		this.memid = memid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemCard
	 *
	 * @return the value of mem.MemCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemcard() {
		return memcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemCard
	 *
	 * @param memcard
	 *            the value for mem.MemCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemcard(String memcard) {
		this.memcard = memcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemPassword
	 *
	 * @return the value of mem.MemPassword
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMempassword() {
		return mempassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemPassword
	 *
	 * @param mempassword
	 *            the value for mem.MemPassword
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMempassword(String mempassword) {
		this.mempassword = mempassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemName
	 *
	 * @return the value of mem.MemName
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemname() {
		return memname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemName
	 *
	 * @param memname
	 *            the value for mem.MemName
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemname(String memname) {
		this.memname = memname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemSex
	 *
	 * @return the value of mem.MemSex
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemsex() {
		return memsex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemSex
	 *
	 * @param memsex
	 *            the value for mem.MemSex
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemsex(Integer memsex) {
		this.memsex = memsex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemIdentityCard
	 *
	 * @return the value of mem.MemIdentityCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemidentitycard() {
		return memidentitycard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemIdentityCard
	 *
	 * @param memidentitycard
	 *            the value for mem.MemIdentityCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemidentitycard(String memidentitycard) {
		this.memidentitycard = memidentitycard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemMobile
	 *
	 * @return the value of mem.MemMobile
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemmobile() {
		return memmobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemMobile
	 *
	 * @param memmobile
	 *            the value for mem.MemMobile
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemmobile(String memmobile) {
		this.memmobile = memmobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemPhoto
	 *
	 * @return the value of mem.MemPhoto
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemphoto() {
		return memphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemPhoto
	 *
	 * @param memphoto
	 *            the value for mem.MemPhoto
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemphoto(String memphoto) {
		this.memphoto = memphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemBirthdayType
	 *
	 * @return the value of mem.MemBirthdayType
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMembirthdaytype() {
		return membirthdaytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemBirthdayType
	 *
	 * @param membirthdaytype
	 *            the value for mem.MemBirthdayType
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMembirthdaytype(Integer membirthdaytype) {
		this.membirthdaytype = membirthdaytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemBirthday
	 *
	 * @return the value of mem.MemBirthday
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMembirthday() {
		return membirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemBirthday
	 *
	 * @param membirthday
	 *            the value for mem.MemBirthday
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMembirthday(String membirthday) {
		this.membirthday = membirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemIsPast
	 *
	 * @return the value of mem.MemIsPast
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemispast() {
		return memispast;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemIsPast
	 *
	 * @param memispast
	 *            the value for mem.MemIsPast
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemispast(Integer memispast) {
		this.memispast = memispast;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemPastTime
	 *
	 * @return the value of mem.MemPastTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMempasttime() {
		return mempasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemPastTime
	 *
	 * @param mempasttime
	 *            the value for mem.MemPastTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMempasttime(String mempasttime) {
		this.mempasttime = mempasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemPoint
	 *
	 * @return the value of mem.MemPoint
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMempoint() {
		return mempoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemPoint
	 *
	 * @param mempoint
	 *            the value for mem.MemPoint
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMempoint(Integer mempoint) {
		this.mempoint = mempoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemPointAutomatic
	 *
	 * @return the value of mem.MemPointAutomatic
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMempointautomatic() {
		return mempointautomatic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemPointAutomatic
	 *
	 * @param mempointautomatic
	 *            the value for mem.MemPointAutomatic
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMempointautomatic(Integer mempointautomatic) {
		this.mempointautomatic = mempointautomatic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemMoney
	 *
	 * @return the value of mem.MemMoney
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public BigDecimal getMemmoney() {
		return memmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemMoney
	 *
	 * @param memmoney
	 *            the value for mem.MemMoney
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemmoney(BigDecimal memmoney) {
		this.memmoney = memmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemConsumeMoney
	 *
	 * @return the value of mem.MemConsumeMoney
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public BigDecimal getMemconsumemoney() {
		return memconsumemoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemConsumeMoney
	 *
	 * @param memconsumemoney
	 *            the value for mem.MemConsumeMoney
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemconsumemoney(BigDecimal memconsumemoney) {
		this.memconsumemoney = memconsumemoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemConsumeLastTime
	 *
	 * @return the value of mem.MemConsumeLastTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Date getMemconsumelasttime() {
		return memconsumelasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemConsumeLastTime
	 *
	 * @param memconsumelasttime
	 *            the value for mem.MemConsumeLastTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemconsumelasttime(Date memconsumelasttime) {
		this.memconsumelasttime = memconsumelasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemConsumeCount
	 *
	 * @return the value of mem.MemConsumeCount
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemconsumecount() {
		return memconsumecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemConsumeCount
	 *
	 * @param memconsumecount
	 *            the value for mem.MemConsumeCount
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemconsumecount(Integer memconsumecount) {
		this.memconsumecount = memconsumecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemEmail
	 *
	 * @return the value of mem.MemEmail
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMememail() {
		return mememail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemEmail
	 *
	 * @param mememail
	 *            the value for mem.MemEmail
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMememail(String mememail) {
		this.mememail = mememail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemAddress
	 *
	 * @return the value of mem.MemAddress
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemaddress() {
		return memaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemAddress
	 *
	 * @param memaddress
	 *            the value for mem.MemAddress
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemaddress(String memaddress) {
		this.memaddress = memaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemState
	 *
	 * @return the value of mem.MemState
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemstate() {
		return memstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemState
	 *
	 * @param memstate
	 *            the value for mem.MemState
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemstate(Integer memstate) {
		this.memstate = memstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemRecommendID
	 *
	 * @return the value of mem.MemRecommendID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemrecommendid() {
		return memrecommendid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemRecommendID
	 *
	 * @param memrecommendid
	 *            the value for mem.MemRecommendID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemrecommendid(Integer memrecommendid) {
		this.memrecommendid = memrecommendid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemLevelID
	 *
	 * @return the value of mem.MemLevelID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemlevelid() {
		return memlevelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemLevelID
	 *
	 * @param memlevelid
	 *            the value for mem.MemLevelID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemlevelid(Integer memlevelid) {
		this.memlevelid = memlevelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemShopID
	 *
	 * @return the value of mem.MemShopID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemshopid() {
		return memshopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemShopID
	 *
	 * @param memshopid
	 *            the value for mem.MemShopID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemshopid(Integer memshopid) {
		this.memshopid = memshopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemCreateTime
	 *
	 * @return the value of mem.MemCreateTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Date getMemcreatetime() {
		return memcreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemCreateTime
	 *
	 * @param memcreatetime
	 *            the value for mem.MemCreateTime
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemcreatetime(Date memcreatetime) {
		this.memcreatetime = memcreatetime;
	}

	public String getMemcreatetimeStr() {
		return DateUtil.format(this.memcreatetime, DateUtil.yyyy_MM_dd_HH_mm_ss);
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemRemark
	 *
	 * @return the value of mem.MemRemark
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemremark() {
		return memremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemRemark
	 *
	 * @param memremark
	 *            the value for mem.MemRemark
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemremark(String memremark) {
		this.memremark = memremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemUserID
	 *
	 * @return the value of mem.MemUserID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemuserid() {
		return memuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemUserID
	 *
	 * @param memuserid
	 *            the value for mem.MemUserID
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemuserid(Integer memuserid) {
		this.memuserid = memuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemTelePhone
	 *
	 * @return the value of mem.MemTelePhone
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemtelephone() {
		return memtelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemTelePhone
	 *
	 * @param memtelephone
	 *            the value for mem.MemTelePhone
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemtelephone(String memtelephone) {
		this.memtelephone = memtelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemQRCode
	 *
	 * @return the value of mem.MemQRCode
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemqrcode() {
		return memqrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemQRCode
	 *
	 * @param memqrcode
	 *            the value for mem.MemQRCode
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemqrcode(String memqrcode) {
		this.memqrcode = memqrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemProvince
	 *
	 * @return the value of mem.MemProvince
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemprovince() {
		return memprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemProvince
	 *
	 * @param memprovince
	 *            the value for mem.MemProvince
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemprovince(String memprovince) {
		this.memprovince = memprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemCity
	 *
	 * @return the value of mem.MemCity
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemcity() {
		return memcity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemCity
	 *
	 * @param memcity
	 *            the value for mem.MemCity
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemcity(String memcity) {
		this.memcity = memcity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemCounty
	 *
	 * @return the value of mem.MemCounty
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemcounty() {
		return memcounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemCounty
	 *
	 * @param memcounty
	 *            the value for mem.MemCounty
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemcounty(String memcounty) {
		this.memcounty = memcounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemVillage
	 *
	 * @return the value of mem.MemVillage
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemvillage() {
		return memvillage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemVillage
	 *
	 * @param memvillage
	 *            the value for mem.MemVillage
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemvillage(String memvillage) {
		this.memvillage = memvillage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemQuestion
	 *
	 * @return the value of mem.MemQuestion
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemquestion() {
		return memquestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemQuestion
	 *
	 * @param memquestion
	 *            the value for mem.MemQuestion
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemquestion(String memquestion) {
		this.memquestion = memquestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemAnswer
	 *
	 * @return the value of mem.MemAnswer
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemanswer() {
		return memanswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemAnswer
	 *
	 * @param memanswer
	 *            the value for mem.MemAnswer
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemanswer(String memanswer) {
		this.memanswer = memanswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemWeiXinCard
	 *
	 * @return the value of mem.MemWeiXinCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemweixincard() {
		return memweixincard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemWeiXinCard
	 *
	 * @param memweixincard
	 *            the value for mem.MemWeiXinCard
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemweixincard(String memweixincard) {
		this.memweixincard = memweixincard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemCardNumber
	 *
	 * @return the value of mem.MemCardNumber
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemcardnumber() {
		return memcardnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemCardNumber
	 *
	 * @param memcardnumber
	 *            the value for mem.MemCardNumber
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemcardnumber(String memcardnumber) {
		this.memcardnumber = memcardnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemAttention
	 *
	 * @return the value of mem.MemAttention
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public Integer getMemattention() {
		return memattention;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemAttention
	 *
	 * @param memattention
	 *            the value for mem.MemAttention
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemattention(Integer memattention) {
		this.memattention = memattention;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mem.MemWeiXinCards
	 *
	 * @return the value of mem.MemWeiXinCards
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemweixincards() {
		return memweixincards;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mem.MemWeiXinCards
	 *
	 * @param memweixincards
	 *            the value for mem.MemWeiXinCards
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public void setMemweixincards(String memweixincards) {
		this.memweixincards = memweixincards;
	}

	public String getShopname() {
		return shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	public String getLevelname() {
		return levelname;
	}

	public void setLevelname(String levelname) {
		this.levelname = levelname;
	}

	public BigDecimal getConsumemoney() {
		return consumemoney;
	}

	public void setConsumemoney(BigDecimal consumemoney) {
		this.consumemoney = consumemoney;
	}

	public double getMemcountnumber() {
		return memcountnumber;
	}

	public void setMemcountnumber(double memcountnumber) {
		this.memcountnumber = memcountnumber;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Map<String, String> getMap() {

		return map;
	}

	public void setMap(Map<String, String> map) {
		this.map = map;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemProvince
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemprovincename() {
		String province = this.getMemprovince();
		if (StringUtil.isNotBlank(province)) {
			for (Sysarea area : MemoryListener.areaList) {
				if (Integer.parseInt(province) == area.getId()) {
					return area.getName();
				}
			}
		}
		return "";

	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCity
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemcityname() {
		String city = this.getMemcity();
		if (StringUtil.isNotBlank(city)) {
			for (Sysarea area : MemoryListener.areaList) {
				if (Integer.parseInt(city) == area.getId()) {
					return area.getName();
				}
			}
		}
		return "";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemCounty
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemcountyname() {
		String county = this.getMemcounty();

		if (StringUtil.isNotBlank(county)) {
			for (Sysarea area : MemoryListener.areaList) {
				if (Integer.parseInt(county) == area.getId()) {
					return area.getName();
				}
			}
		}

		return "";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mem.MemVillage
	 *
	 * @mbggenerated Mon Nov 30 16:11:47 CST 2015
	 */
	public String getMemvillagename() {
		String village = this.getMemvillage();
		if (StringUtil.isNotBlank(village)) {
			for (Sysarea area : MemoryListener.areaList) {
				if (Integer.parseInt(village) == area.getId()) {
					return area.getName();
				}
			}
		}
		return "";

	}

}