package com.jfxy.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.jfxy.util.StringUtil;

public class RptMem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.MemID
     *
     * @mbggenerated Mon Nov 30 16:11:47 CST 2015
     */
    private Integer memid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.MemCard
     *
     * @mbggenerated Mon Nov 30 16:11:47 CST 2015
     */
    private String memcard;

    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem.MemName
     *
     * @mbggenerated Mon Nov 30 16:11:47 CST 2015
     */
    private String memname;
    
    /**
     * shopname
     */
    private String shopname;

   

  

	
    
    /**
     * consumemoney
     */
    private BigDecimal consumemoney;
    
    
    private BigDecimal discountmoney;
    
    
    
    private List<Orderlog> orderlogList=new ArrayList<Orderlog>();



	public Integer getMemid() {
		return memid;
	}



	public void setMemid(Integer memid) {
		this.memid = memid;
	}



	public String getMemcard() {
		return memcard;
	}



	public void setMemcard(String memcard) {
		this.memcard = memcard;
	}



	public String getMemname() {
		return memname;
	}



	public void setMemname(String memname) {
		this.memname = memname;
	}



	public String getShopname() {
		return shopname;
	}



	public void setShopname(String shopname) {
		this.shopname = shopname;
	}



	public BigDecimal getConsumemoney() {
		return consumemoney;
	}



	public void setConsumemoney(BigDecimal consumemoney) {
		this.consumemoney = consumemoney;
	}



	public List<Orderlog> getOrderlogList() {
		return orderlogList;
	}



	public void setOrderlogList(List<Orderlog> orderlogList) {
		this.orderlogList = orderlogList;
	}



	public BigDecimal getDiscountmoney() {
		return discountmoney;
	}



	public void setDiscountmoney(BigDecimal discountmoney) {
		this.discountmoney = discountmoney;
	}
    
    
    
	
    
    
}