package com.jfxy.pojo.form;

import java.util.Date;

import com.jfxy.pojo.Sysuser;
import com.jfxy.util.Pagination;



public class SysuserFormBean extends Pagination<Sysuser> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserAccount
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserName
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserPassword
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserShopID
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private Integer usershopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserGroupID
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private Integer usergroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserLock
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private Byte userlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserRemark
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private String userremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserCreateTime
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private Date usercreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserTelephone
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private String usertelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.UserNumber
     *
     * @mbggenerated Fri Nov 27 14:40:05 CST 2015
     */
    private String usernumber;

	public String getUseraccount() {
		return useraccount;
	}

	public void setUseraccount(String useraccount) {
		this.useraccount = useraccount;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpassword() {
		return userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	public Integer getUsershopid() {
		return usershopid;
	}

	public void setUsershopid(Integer usershopid) {
		this.usershopid = usershopid;
	}

	public Integer getUsergroupid() {
		return usergroupid;
	}

	public void setUsergroupid(Integer usergroupid) {
		this.usergroupid = usergroupid;
	}

	public Byte getUserlock() {
		return userlock;
	}

	public void setUserlock(Byte userlock) {
		this.userlock = userlock;
	}

	public String getUserremark() {
		return userremark;
	}

	public void setUserremark(String userremark) {
		this.userremark = userremark;
	}

	public Date getUsercreatetime() {
		return usercreatetime;
	}

	public void setUsercreatetime(Date usercreatetime) {
		this.usercreatetime = usercreatetime;
	}

	public String getUsertelephone() {
		return usertelephone;
	}

	public void setUsertelephone(String usertelephone) {
		this.usertelephone = usertelephone;
	}

	public String getUsernumber() {
		return usernumber;
	}

	public void setUsernumber(String usernumber) {
		this.usernumber = usernumber;
	}
    
    
    
	
	
}
